<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<link rel="icon" href="favicon.ico" type="image/x-icon" />
<link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Kira Manager</title>
</head>
<body>
	<p />
	<br />
	<a href="getCheckInfo.hck?type=YDD,META-INF">HealthCheck(getCheckInfo.hck?type=YDD,META-INF)</a>
	<p />
	<br />
	<a href="login/doLogin.action">login/doLogin.action</a>
	<p />
	<br />
	<a href="jobStatus/list.action">jobStatus/list.action</a>
	<p />
	<br />
	<a href="jobStatus/list.action?criteria.id=1&criteria.paging.maxResults=100&criteria.orderByClause=id desc">jobStatus/list.action?criteria.id=1&criteria.paging.maxResults=100&criteria.orderByClause=id desc</a>	
	<p />
	<br />
	<a href="menu/getMenuTree.action">查询功能菜单树(menu/getMenuTree.action)</a>	
	<p />
	<br />
	<a href="user/getLoginUserContextData.action">获取登录用户相关信息(user/getLoginUserContextData.action)</a>
	<p />
	<br />
	<a href="other/getCurrentServerIp.action">获取当前服务器IP(other/getCurrentServerIp.action)</a>
	<p />
	<br />
	<a href="other/getKiraZoneContextData.action">获取kira的zone相关信息。(other/getKiraZoneContextData.action)</a>	
	<p />
	<br />
	<a href="other/getChildsUnderTriggersZNode.action">getChildsUnderTriggersZNode(other/getChildsUnderTriggersZNode.action)</a>
	<p />
	<br />
	<a href="other/getPoolsZNodeValueUnderTriggersZNode.action">getPoolsZNodeValueUnderTriggersZNode(other/getPoolsZNodeValueUnderTriggersZNode.action)</a>
	<p />
	<br />	
	<a href="other/getAdminUserNames.action">getAdminUserNames(other/getAdminUserNames.action)</a>
	<p />
	<br />
	<a href="other/setAdminUserNames.action?criteria.adminUserNames=xxx">setAdminUserNames(other/setAdminUserNames.action?criteria.adminUserNames=xxx)</a>
	<p />
	<br />
	<a href="other/getPoolValueNeedRectifiedPoolsUnderTriggers.action">getPoolValueNeedRectifiedPoolsUnderTriggers(other/getPoolValueNeedRectifiedPoolsUnderTriggers.action)</a>	
	<p />
	<br />
	<a href="other/rectifyValueOfPoolNodesUnderTriggers.action">rectifyValueOfPoolNodesUnderTriggers(other/rectifyValueOfPoolNodesUnderTriggers.action)</a>			
	<p />
	<br />	
	<a href="other/isNeedArchiveJobRuntimeData.action">isNeedArchiveJobRuntimeData(other/isNeedArchiveJobRuntimeData.action)</a>			
	<p />
	<br />
	<a href="other/setNeedArchiveJobRuntimeData.action?criteria.needArchiveJobRuntimeData=false">setNeedArchiveJobRuntimeData(other/setNeedArchiveJobRuntimeData.action?criteria.needArchiveJobRuntimeData=false)</a>
	<p />
	<br />
	<a href="other/getMinutesToKeepJobRuntimeData.action">getMinutesToKeepJobRuntimeData(other/getMinutesToKeepJobRuntimeData.action)</a>			
	<p />
	<br />
	<a href="other/setMinutesToKeepJobRuntimeData.action?criteria.minutesToKeepJobRuntimeData=">setMinutesToKeepJobRuntimeData(other/setMinutesToKeepJobRuntimeData.action?criteria.minutesToKeepJobRuntimeData=)</a>
	<p />
	<br />
	<a href="other/getMinutesPerTimeToHandleJobRuntimeData.action">getMinutesPerTimeToHandleJobRuntimeData(other/getMinutesPerTimeToHandleJobRuntimeData.action)</a>			
	<p />
	<br />
	<a href="other/setMinutesPerTimeToHandleJobRuntimeData.action?criteria.minutesPerTimeToHandleJobRuntimeData=">setMinutesPerTimeToHandleJobRuntimeData(other/setMinutesPerTimeToHandleJobRuntimeData.action?criteria.minutesPerTimeToHandleJobRuntimeData=)</a>
	<p />
	<br />	
	<a href="other/getSleepTimeBeforeRunNextTaskInMilliseconds.action">getSleepTimeBeforeRunNextTaskInMilliseconds(other/getSleepTimeBeforeRunNextTaskInMilliseconds.action)</a>			
	<p />
	<br />
	<a href="other/setSleepTimeBeforeRunNextTaskInMilliseconds.action?criteria.sleepTimeBeforeRunNextTaskInMilliseconds=60000">setSleepTimeBeforeRunNextTaskInMilliseconds(other/setSleepTimeBeforeRunNextTaskInMilliseconds.action?criteria.sleepTimeBeforeRunNextTaskInMilliseconds=60000)</a>
	<p />
	<br />	
	<a href="other/getTimeOutPerTaskInMilliseconds.action">getTimeOutPerTaskInMilliseconds(other/getTimeOutPerTaskInMilliseconds.action)</a>			
	<p />
	<br />
	<a href="other/setTimeOutPerTaskInMilliseconds.action?criteria.timeOutPerTaskInMilliseconds=60000">setTimeOutPerTaskInMilliseconds(other/setTimeOutPerTaskInMilliseconds.action?criteria.timeOutPerTaskInMilliseconds=60000)</a>
	<p />
	<br />
	<a href="other/getPrivateEmails.action">getPrivateEmails(other/getPrivateEmails.action)</a>
	<p />
	<br />	
	<a href="other/setPrivateEmails.action?criteria.privateEmails=xxx">setPrivateEmails(other/setPrivateEmails.action?criteria.privateEmails=xxx)</a>
	<p />
	<br />
	<a href="other/getPrivatePhoneNumbers.action">getPrivatePhoneNumbers(other/getPrivatePhoneNumbers.action)</a>
	<p />
	<br />	
	<a href="other/setPrivatePhoneNumbers.action?criteria.privatePhoneNumbers=xxx">setPrivatePhoneNumbers(other/setPrivatePhoneNumbers.action?criteria.privatePhoneNumbers=xxx)</a>
	<p />
	<br />				
	<a href="other/getAdminEmails.action">getAdminEmails(other/getAdminEmails.action)</a>
	<p />
	<br />	
	<a href="other/setAdminEmails.action?criteria.adminEmails=xxx">setAdminEmails(other/setAdminEmails.action?criteria.adminEmails=xxx)</a>
	<p />
	<br />	
	<a href="other/getAdminPhoneNumbers.action">getAdminPhoneNumbers(other/getAdminPhoneNumbers.action)</a>
	<p />
	<br />	
	<a href="other/setAdminPhoneNumbers.action?criteria.adminPhoneNumbers=">setAdminPhoneNumbers(other/setAdminPhoneNumbers.action?criteria.adminPhoneNumbers=)</a>
	<p />
	<br />
	<a href="other/getHealthEventReceiverEmails.action">getHealthEventReceiverEmails(other/getHealthEventReceiverEmails.action)</a>
	<p />
	<br />
	<a href="other/setHealthEventReceiverEmails.action?criteria.healthEventReceiverEmails=">setHealthEventReceiverEmails(other/setHealthEventReceiverEmails.action?criteria.healthEventReceiverEmails=)</a>
	<p />
	<br />
	<a href="other/getHealthEventReceiverPhoneNumbers.action">getHealthEventReceiverPhoneNumbers(other/getHealthEventReceiverPhoneNumbers.action)</a>
	<p />
	<br />
	<a href="other/setHealthEventReceiverPhoneNumbers.action?criteria.healthEventReceiverPhoneNumbers=">setHealthEventReceiverPhoneNumbers(other/setHealthEventReceiverPhoneNumbers.action?criteria.healthEventReceiverPhoneNumbers=)</a>
	<p />
	<br />							
	<a href="other/getChildsUnderZNnodeFullPath.action?criteria.znodeFullPath=">getChildsUnderZNnodeFullPath(other/getChildsUnderZNnodeFullPath.action?criteria.znodeFullPath=)</a>
	<p />
	<br />						
	<a href="other/getZNodeValueOfZNnodeFullPath.action?criteria.znodeFullPath=">getZNodeValueOfZNnodeFullPath(other/getZNodeValueOfZNnodeFullPath.action?criteria.znodeFullPath=)</a>
	<p />
	<br />	
	<a href="other/getJobTimeoutHandleFailedMaxCount.action">getJobTimeoutHandleFailedMaxCount(other/getJobTimeoutHandleFailedMaxCount.action)</a>		
	<p />
	<br />	
	<a href="other/setJobTimeoutHandleFailedMaxCount.action?criteria.jobTimeoutHandleFailedMaxCount=">setJobTimeoutHandleFailedMaxCount(other/setJobTimeoutHandleFailedMaxCount.action?criteria.jobTimeoutHandleFailedMaxCount=)</a>			
	<p />
	<br />
	<a href="other/getInValidRunningEnvironmentListForTimerTrigger.action">getInValidRunningEnvironmentListForTimerTrigger(other/getInValidRunningEnvironmentListForTimerTrigger.action)</a>		
	<p />
	<br />
	<a href="other/cleanInValidEnvironmentsForTimerTrigger.action">cleanInValidEnvironmentsForTimerTrigger(other/cleanInValidEnvironmentsForTimerTrigger.action)</a>		
	<p />
	<br />
	<a href="other/exportTriggersPredictReport.action">exportTriggersPredictReport(other/exportTriggersPredictReport.action)</a>		
	<p />
	<br />
	<a href="other/cleanForAllUnusedPools.action">cleanForAllUnusedPools(other/cleanForAllUnusedPools.action)</a>
	<p />
	<br />								
	<a href="kiraClient/queryKiraClientInfoAsMap.action?criteria.centralScheduleServiceUrl=">获取Kira客户端当前信息(kiraClient/queryKiraClientInfoAsMap.action?criteria.centralScheduleServiceUrl=)</a>																			
	<p />	
	<br />
	<a href="kiraClientMetadata/listOnPage.action?criteria.paging.maxResults=1">分页查询各pool的kira客户端配置信息(kiraClientMetadata/listOnPage.action?criteria.paging.maxResults=1)</a>																			
	<p />	
	<br />
	<a href="kiraClientMetadata/getAllPoolIdList.action">获取Kira客户端对应的所有PoolId列表(kiraClientMetadata/getAllPoolIdList.action)</a>
	<p />	
	<br />
	<a href="kiraClientMetadata/getAllAvailablePoolIdList.action">获取Kira客户端对应的所有可用的PoolId列表(kiraClientMetadata/getAllAvailablePoolIdList.action)</a>																																							
	<p />	
	<br />	
	<a href="kiraClientMetadata/getKiraClientMetadataById.action?criteria.id=1">根据Id获取Kira客户端配置信息(kiraClientMetadata/getKiraClientMetadataById.action?criteria.id=1)</a>
	<p />	
	<br />	
	<a href="kiraClientMetadata/updateKiraClientMetadata.action?kiraClientMetadata.id=1&kiraClientMetadata.visibilityLimited=true&kiraClientMetadata.visibleForUsers=testName1,testName2&kiraClientMetadata.sendAlarmEmail=true&kiraClientMetadata.emailsToReceiveAlarm=xxx&kiraClientMetadata.sendAlarmSMS=true&kiraClientMetadata.phoneNumbersToReceiveAlarmSMS=XXX">更新Kira客户端配置信息(kiraClientMetadata/updateKiraClientMetadata.action?kiraClientMetadata.id=1&kiraClientMetadata.visibilityLimited=true&kiraClientMetadata.visibleForUsers=testName1,testName2&kiraClientMetadata.sendAlarmEmail=true&kiraClientMetadata.emailsToReceiveAlarm=xxx&kiraClientMetadata.sendAlarmSMS=true&kiraClientMetadata.phoneNumbersToReceiveAlarmSMS=xxx,xxx)</a>
	<p />	
	<br />		
	<a href="kiraClientMetadata/createKiraClientMetadata.action?newKiraClientMetadata.poolId=myNewPoolId&newKiraClientMetadata.manuallyCreatedDetail=createPoolTest">创建Kira客户端配置信息(kiraClientMetadata/createKiraClientMetadata.action?newKiraClientMetadata.poolId=myNewPoolId&newKiraClientMetadata.manuallyCreatedDetail=createPoolTest)</a>																																							
	<p />	
	<br />
	<a href="kiraClientMetadata/deleteKiraClientMetadata.action?criteria.poolId=kira">删除非手动创建的Kira客户端配置信息(会连带删除其下所有的定时任务)(kiraClientMetadata/deleteKiraClientMetadata.action?criteria.poolId=kira)</a>
	<p />	
	<br />
	<a href="kiraClientMetadata/deleteKiraClientMetadata.action?criteria.poolId=myCreatedPoolId">删除手动创建的Kira客户端配置信息(会连带删除其下所有的定时任务)(kiraClientMetadata/deleteKiraClientMetadata.action?criteria.poolId=myCreatedPoolId)</a>																																							
	<p />	
	<br />	
	<a href="triggerMetadata/listLatest.action">triggerMetadata/listLatest.action</a>
	<p />
	<br />
	<a href="triggerMetadata/listOnPage.action?criteria.paging.maxResults=15&criteria.poolId=yihaodian/web-pool-simulator&criteria.triggerId=yhdCronTrigger_kiraClientTestCanceledFailedService-executeJobFailed-asynchronous-onlyRunOnSingleProcess">定时任务各版本配置信息查询(triggerMetadata/listOnPage.action?criteria.paging.maxResults=15&criteria.poolId=yihaodian/web-pool-simulator&criteria.triggerId=yhdCronTrigger_kiraClientTestCanceledFailedService-executeJobFailed-asynchronous-onlyRunOnSingleProcess)</a>			
	<p />
	<br />
	<a href="triggerMetadata/getAllPoolIdTriggerIdsMap.action">获取PoolId和对应的triggerIds对应关系(triggerMetadata/getAllPoolIdTriggerIdsMap.action)</a>
	<p />
	<br />
	<a href="triggerMetadata/getAllPoolIdList.action">获取所有PoolId列表(triggerMetadata/getAllPoolIdList.action)</a>
	<p />
	<br />
	<a href="triggerMetadata/getAllTriggerIdList.action?criteria.poolId=yihaodian/web-pool-simulator">获取某个PoolId对应的所有triggerId列表(triggerMetadata/getAllTriggerIdList.action?criteria.poolId=yihaodian/web-pool-simulator)</a>
	<p />
	<br />
	<a href="triggerMetadata/getAllAvailableTriggerIdList.action?criteria.poolId=yihaodian/web-pool-simulator">获取某个PoolId对应的所有可用的triggerId列表(triggerMetadata/getAllAvailableTriggerIdList.action?criteria.poolId=yihaodian/web-pool-simulator)</a>					
	<p />
	<br />
	<a href="triggerMetadata/getPoolTriggerStatus.action?criteria.poolId=yihaodian/web-pool-simulator&criteria.triggerId=yhdCronTrigger_kiraClientTestCanceledFailedService-executeJobFailed-asynchronous-onlyRunOnSingleProcess">获取某个定时任务的最新调度状态信息(triggerMetadata/getPoolTriggerStatus.action?criteria.poolId=yihaodian/web-pool-simulator&criteria.triggerId=yhdCronTrigger_kiraClientTestCanceledFailedService-executeJobFailed-asynchronous-onlyRunOnSingleProcess)</a>
	<p />
	<br />
	<a href="triggerMetadata/getPoolTriggerStatusListOnPage.action?criteria.paging.maxResults=30&criteria.poolId=yihaodian/web-pool-simulator">获取定时任务的最新调度状态信息列表(triggerMetadata/getPoolTriggerStatusListOnPage.action?criteria.poolId=yihaodian/web-pool-simulator)</a>	
	<p />
	<br />
	<a href="triggerMetadata/getTriggerEnvironmentDetailDataListOnPage.action?criteria.poolId=yihaodian/web-pool-simulator&criteria.triggerId=yhdCronTrigger_kiraClientTestCanceledFailedService-executeJobFailed-asynchronous-onlyRunOnSingleProcess">获取某个定时任务的执行环境信息(triggerMetadata/getTriggerEnvironmentDetailDataListOnPage.action?criteria.poolId=yihaodian/web-pool-simulator&criteria.triggerId=yhdCronTrigger_kiraClientTestCanceledFailedService-executeJobFailed-asynchronous-onlyRunOnSingleProcess)</a>					
	<p />
	<br />
	<a href="triggerMetadata/listLatestOnPage.action?criteria.paging.maxResults=30&criteria.paging.currentPage=1">定时任务列表(triggerMetadata/listLatestOnPage.action?criteria.paging.maxResults=30&criteria.paging.currentPage=1)</a>
	<p />
	<br />
	<a href="triggerMetadata/updateTriggersAsUnRegistered.action?criteria.poolId=yihaodian/web-pool-simulator&criteria.triggerId=yhdCronTrigger_kiraClientTestCanceledFailedService-executeJobFailed-asynchronous-onlyRunOnSingleProcess&criteria.version=0.0.1">更新某个定时任务为未注册状态(triggerMetadata/updateTriggersAsUnRegistered.action?criteria.poolId=yihaodian/web-pool-simulator&criteria.triggerId=yhdCronTrigger_kiraClientTestCanceledFailedService-executeJobFailed-asynchronous-onlyRunOnSingleProcess&criteria.version=0.0.1)</a>
	<p />
	<br />
	<a href="triggerMetadata/rescheduleJob.action?criteria.poolId=yihaodian/web-pool-simulator&criteria.triggerId=yhdSimpleTrigger_kiraClientTestService-executeJobSuccess-asynchronous-onlyRunOnSingleProcess-repeatCount2-misfireInstruction1">重新进行某个定时任务调度(triggerMetadata/rescheduleJob.action?criteria.poolId=yihaodian/web-pool-simulator&criteria.triggerId=yhdSimpleTrigger_kiraClientTestService-executeJobSuccess-asynchronous-onlyRunOnSingleProcess-repeatCount2-misfireInstruction1)</a>
	<p />
	<br />
	<a href="triggerMetadata/deleteTrigger.action?criteria.poolId=yihaodian/web-pool-simulator&criteria.triggerId=yhdSimpleTrigger_kiraClientTestService-executeJobSuccess-asynchronous-onlyRunOnSingleProcess-repeatCount2-misfireInstruction1&criteria.version=0.0.1">删除某个非手动创建的定时任务(triggerMetadata/deleteTrigger.action?criteria.poolId=yihaodian/web-pool-simulator&criteria.triggerId=yhdSimpleTrigger_kiraClientTestService-executeJobSuccess-asynchronous-onlyRunOnSingleProcess-repeatCount2-misfireInstruction1&criteria.version=0.0.1)</a>
	<p />
	<br />
	<a href="triggerMetadata/deleteTrigger.action?criteria.poolId=myCreatedPoolId&criteria.triggerId=myCreatedSimpleTriggerId&criteria.version=0.0.1">删除某个手动创建的定时任务(triggerMetadata/deleteTrigger.action?criteria.poolId=myCreatedPoolId&criteria.triggerId=myCreatedSimpleTriggerId&criteria.version=0.0.1)</a>	
	<p />
	<br />
	<a href="triggerMetadata/manuallyRunJobByTriggerMetadata.action?criteria.poolId=yihaodian/web-pool-simulator&criteria.triggerId=yhdCronTrigger_kiraClientTestService-executeJobSuccess-asynchronous-canRunOnMultiProcess">手动执行某个定时任务(triggerMetadata/manuallyRunJobByTriggerMetadata.action?criteria.poolId=yihaodian/web-pool-simulator&criteria.triggerId=yhdCronTrigger_kiraClientTestService-executeJobSuccess-asynchronous-canRunOnMultiProcess)</a>
	<p />
	<br />
	<a href="triggerMetadata/deleteTriggerEnvironment.action?criteria.triggerEnvironmentZKFullPath=">删除执行环境(triggerMetadata/deleteTriggerEnvironment.action?criteria.triggerEnvironmentZKFullPath=)</a>
	<p />
	<br />
	<a href="triggerMetadata/getTriggerMetadataById.action?criteria.id=1">根据id获得调度任务的详细配置信息(triggerMetadata/getTriggerMetadataById.action?criteria.id=1)</a>		
	<p />
	<br />
	<a href="triggerMetadata/getTriggerTypeList.action">获得所有调度任务类型列表(triggerMetadata/getTriggerTypeList.action)</a>
	<p />
	<br />
	<a href="triggerMetadata/getMisfireInstructionList.action?criteria.triggerType=SimpleTrigger">根据调度任务类型(SimpleTrigger 或者  CronTrigger)获得漏执行策略列表(triggerMetadata/getMisfireInstructionList.action?criteria.triggerType=SimpleTrigger)</a>	
	<p />
	<br />
	<a href="triggerMetadata/updateTrigger.action?triggerMetadata.id=&triggerMetadata.targetMethod=executeJobSuccess&triggerMetadata.targetMethodArgTypes=['java.util.LinkedHashMap']&triggerMetadata.triggerType=SimpleTrigger&triggerMetadata.startTimeAsString=&triggerMetadata.endTimeAsString=&triggerMetadata.startDelay=20000&triggerMetadata.repeatCount=3&triggerMetadata.repeatInterval=60000&triggerMetadata.cronExpression=&triggerMetadata.description=被更新为启动延迟20秒每1分钟总共执行四次的异步多台机器执行的misfireInstruction为4的非本地可用的执行成功的方法带执行参数的SimpleTrigger&triggerMetadata.misfireInstruction=4&triggerMetadata.asynchronous=true&triggerMetadata.onlyRunOnSingleProcess=false&triggerMetadata.disabled=false&triggerMetadata.argumentsAsJsonArrayString=[{'key_A':'value_A','key_B':'value_B'}]">更新调度任务为SimpleTrigger(triggerMetadata/updateTrigger.action?triggerMetadata.id=&triggerMetadata.targetMethod=executeJobSuccess&triggerMetadata.targetMethodArgTypes=['java.util.LinkedHashMap']&triggerMetadata.triggerType=SimpleTrigger&triggerMetadata.startTimeAsString=&triggerMetadata.endTimeAsString=&triggerMetadata.startDelay=20000&triggerMetadata.repeatCount=&triggerMetadata.repeatInterval=60000&triggerMetadata.cronExpression=&triggerMetadata.description=被更新为异步多台机器执行的misfireInstruction为4的非本地可用的执行成功的方法带执行参数的SimpleTrigger&triggerMetadata.misfireInstruction=4&triggerMetadata.asynchronous=true&triggerMetadata.onlyRunOnSingleProcess=false&triggerMetadata.disabled=false&triggerMetadata.argumentsAsJsonArrayString=[{'key_A':'value_A','key_B':'value_B'}])</a>
	<p />
	<br />
	<a href="triggerMetadata/updateTrigger.action?triggerMetadata.id=&triggerMetadata.targetMethod=executeJobSuccess&triggerMetadata.targetMethodArgTypes=['java.util.LinkedHashMap']&triggerMetadata.triggerType=CronTrigger&triggerMetadata.startTimeAsString=&triggerMetadata.endTimeAsString=&triggerMetadata.startDelay=&triggerMetadata.repeatCount=&triggerMetadata.repeatInterval=&triggerMetadata.cronExpression=0 0/2 * * * ?&triggerMetadata.description=被更新为每2分钟异步多台机器执行的misfireInstruction为2的非本地可用的执行成功的方法带执行参数的SimpleTrigger&triggerMetadata.misfireInstruction=2&triggerMetadata.asynchronous=true&triggerMetadata.onlyRunOnSingleProcess=false&triggerMetadata.scheduledLocally=false&triggerMetadata.disabled=false&triggerMetadata.argumentsAsJsonArrayString=[{'key_First':'value_First','key_Second':'value_Second'}]">更新调度任务为CronTrigger(triggerMetadata/updateTrigger.action?triggerMetadata.id=&triggerMetadata.targetMethod=executeJobSuccess&triggerMetadata.targetMethodArgTypes=['java.util.LinkedHashMap']&triggerMetadata.triggerType=CronTrigger&triggerMetadata.startTimeAsString=&triggerMetadata.endTimeAsString=&triggerMetadata.startDelay=&triggerMetadata.repeatCount=&triggerMetadata.repeatInterval=&triggerMetadata.cronExpression=0 0/2 * * * ?&triggerMetadata.description=被更新为每2分钟异步多台机器执行的misfireInstruction为2的非本地可用的执行成功的方法带执行参数的SimpleTrigger&triggerMetadata.misfireInstruction=2&triggerMetadata.asynchronous=true&triggerMetadata.onlyRunOnSingleProcess=false&triggerMetadata.scheduledLocally=false&triggerMetadata.disabled=false&triggerMetadata.argumentsAsJsonArrayString=[{'key_First':'value_First','key_Second':'value_Second'}])</a>																																																																																																																															
	<p />
	<br />
	<a href="triggerMetadata/createTrigger.action?newTriggerMetadata.startTimeAsString=2013-12-24 01:02:03&newTriggerMetadata.endTimeAsString=2015-12-24 04:05:06&newTriggerMetadata.poolId=myCreatedPoolId&newTriggerMetadata.triggerId=myCreatedSimpleTriggerId&newTriggerMetadata.version=0.0.1&newTriggerMetadata.targetPoolId=yihaodian/web-pool-simulator&newTriggerMetadata.targetTriggerId=yhdSimpleTrigger_kiraClientTestService-executeJobSuccess-asynchronous-onlyRunOnSingleProcess&newTriggerMetadata.targetMethod=&newTriggerMetadata.targetMethodArgTypes=&newTriggerMetadata.argumentsAsJsonArrayString=[]&newTriggerMetadata.triggerType=SimpleTrigger&newTriggerMetadata.startDelay=10000&newTriggerMetadata.repeatCount=20000000&newTriggerMetadata.repeatInterval=20000&newTriggerMetadata.cronExpression=&newTriggerMetadata.description=myDescription&newTriggerMetadata.misfireInstruction=1&newTriggerMetadata.asynchronous=true&newTriggerMetadata.onlyRunOnSingleProcess=true&newTriggerMetadata.locationsToRunJob=127.0.0.1:80&newTriggerMetadata.scheduledLocally=&newTriggerMetadata.disabled=false">创建SimpleTrigger类型的定时任务(triggerMetadata/createTrigger.action?newTriggerMetadata.startTimeAsString=2013-12-24 01:02:03&newTriggerMetadata.endTimeAsString=2015-12-24 04:05:06&newTriggerMetadata.poolId=myCreatedPoolId&newTriggerMetadata.triggerId=myCreatedTriggerId&newTriggerMetadata.version=0.0.1&newTriggerMetadata.targetPoolId=yihaodian/web-pool-simulator&newTriggerMetadata.targetTriggerId=yhdSimpleTrigger_kiraClientTestService-executeJobSuccess-asynchronous-onlyRunOnSingleProcess&newTriggerMetadata.targetMethod=&newTriggerMetadata.targetMethodArgTypes=&newTriggerMetadata.argumentsAsJsonArrayString=[]&newTriggerMetadata.triggerType=SimpleTrigger&newTriggerMetadata.startDelay=10000&newTriggerMetadata.repeatCount=20&newTriggerMetadata.repeatInterval=20000&newTriggerMetadata.cronExpression=&newTriggerMetadata.description=myDescription&newTriggerMetadata.misfireInstruction=1&newTriggerMetadata.asynchronous=true&newTriggerMetadata.onlyRunOnSingleProcess=true&newTriggerMetadata.locationsToRunJob=127.0.0.1:80&newTriggerMetadata.scheduledLocally=&newTriggerMetadata.disabled=false)</a>																																																																																																																															
	<p />
	<br />
	<a href="triggerMetadata/createTrigger.action?newTriggerMetadata.startTimeAsString=2013-12-24 11:12:13&newTriggerMetadata.endTimeAsString=2015-12-24 14:15:16&newTriggerMetadata.poolId=myCreatedPoolId&newTriggerMetadata.triggerId=myCreatedCronTriggerId&newTriggerMetadata.version=0.0.1&newTriggerMetadata.targetPoolId=yihaodian/web-pool-simulator&newTriggerMetadata.targetTriggerId=yhdSimpleTrigger_kiraClientTestService-executeJobSuccess-asynchronous-onlyRunOnSingleProcess&newTriggerMetadata.targetMethod=&newTriggerMetadata.targetMethodArgTypes=&newTriggerMetadata.argumentsAsJsonArrayString=[]&newTriggerMetadata.triggerType=CronTrigger&newTriggerMetadata.startDelay=&newTriggerMetadata.repeatCount=&newTriggerMetadata.repeatInterval=&newTriggerMetadata.cronExpression=0 30 0 * * ?&newTriggerMetadata.description=myDescription&newTriggerMetadata.misfireInstruction=2&newTriggerMetadata.asynchronous=true&newTriggerMetadata.onlyRunOnSingleProcess=true&newTriggerMetadata.locationsToRunJob=127.0.0.1:80&newTriggerMetadata.scheduledLocally=&newTriggerMetadata.disabled=false">创建CronTrigger类型的定时任务(triggerMetadata/createTrigger.action?newTriggerMetadata.startTimeAsString=2013-12-24 11:12:13&newTriggerMetadata.endTimeAsString=2015-12-24 14:15:16&newTriggerMetadata.poolId=myCreatedPoolId&newTriggerMetadata.triggerId=myCreatedCronTriggerId&newTriggerMetadata.version=0.0.1&newTriggerMetadata.targetPoolId=yihaodian/web-pool-simulator&newTriggerMetadata.targetTriggerId=yhdSimpleTrigger_kiraClientTestService-executeJobSuccess-asynchronous-onlyRunOnSingleProcess&newTriggerMetadata.targetMethod=&newTriggerMetadata.targetMethodArgTypes=&newTriggerMetadata.argumentsAsJsonArrayString=[]&newTriggerMetadata.triggerType=CronTrigger&newTriggerMetadata.startDelay=&newTriggerMetadata.repeatCount=&newTriggerMetadata.repeatInterval=&newTriggerMetadata.cronExpression=0 30 0 * * ?&newTriggerMetadata.description=myDescription&newTriggerMetadata.misfireInstruction=2&newTriggerMetadata.asynchronous=true&newTriggerMetadata.onlyRunOnSingleProcess=true&newTriggerMetadata.locationsToRunJob=127.0.0.1:80&newTriggerMetadata.scheduledLocally=&newTriggerMetadata.disabled=false)</a>
	<p />																																																																																																																																<p />
	<br />
	<a href="triggerMetadata/getLatestTriggerMetadatasWhichSetTriggerAsTargetOnPage.action?criteria.poolId=yihaodian/web-pool-simulator&criteria.triggerId=yhdSimpleTrigger_kiraClientTestService-executeJobSuccess-asynchronous-onlyRunOnSingleProcess&criteria.paging.maxResults=15">查询以某个定时任务所暴露的服务方法为执行目标的定时任务列表信息(triggerMetadata/getLatestTriggerMetadatasWhichSetTriggerAsTargetOnPage.action?criteria.poolId=yihaodian/web-pool-simulator&criteria.triggerId=yhdSimpleTrigger_kiraClientTestService-executeJobSuccess-asynchronous-onlyRunOnSingleProcess&criteria.paging.maxResults=15)</a>																																																																																																																															
	<p />																																																																																																																																<p />
	<br />
	<a href="triggerMetadata/getLatestTriggerMetadatasWhichSetTriggersOfPoolAsTargetOnPage.action?criteria.poolId=yihaodian/web-pool-simulator&criteria.paging.maxResults=15">查询以某个Pool的那些定时任务所暴露的服务方法为执行目标的定时任务列表信息(triggerMetadata/getLatestTriggerMetadatasWhichSetTriggersOfPoolAsTargetOnPage.action?criteria.poolId=yihaodian/web-pool-simulator&criteria.paging.maxResults=15)</a>
	<p />																																																																																																																																<p />
	<br />
	<a href="triggerMetadata/getKiraTimerTriggerBusinessRunningInstanceListOnPage.action?criteria.poolId=yihaodian/web-pool-simulator&criteria.triggerId=yhdCronTrigger_kiraClientTestCanceledFailedService-executeJobSuccess-asynchronous-onlyRunOnSingleProcess">查询定时任务对应的业务方法当前执行实例列表(triggerMetadata/getKiraTimerTriggerBusinessRunningInstanceListOnPage.action?criteria.poolId=yihaodian/web-pool-simulator&criteria.triggerId=yhdCronTrigger_kiraClientTestCanceledFailedService-executeJobSuccess-asynchronous-onlyRunOnSingleProcess)</a>
	<p />
	<br />	
	<a href="jobStatus/listOnPage.action?criteria.paging.maxResults=20&criteria.paging.currentPage=1">定时任务状态说明(jobStatus/listOnPage.action?criteria.paging.maxResults=3&criteria.paging.currentPage=1)</a>	
	<p />
	<br />
	<a href="job/getJobDetailDataListOnPage.action?criteria.paging.maxResults=40&criteria.paging.currentPage=1&criteria.poolId=yihaodian/web-pool-simulator&criteria.triggerId=yhdCronTrigger_kiraClientTestCanceledFailedService-executeJobFailed-asynchronous-onlyRunOnSingleProcess&criteria.jobStatusId=8">定时任务执行情况查询(job/getJobDetailDataListOnPage.action?criteria.paging.maxResults=40&criteria.paging.currentPage=1&criteria.poolId=yihaodian/web-pool-simulator&criteria.triggerId=yhdCronTrigger_kiraClientTestCanceledFailedService-executeJobFailed-asynchronous-onlyRunOnSingleProcess&criteria.jobStatusId=8)</a>
	<p />
	<br />
	<a href="job/getJobDetailDataListOnPage.action?criteria.paging.maxResults=40&criteria.paging.currentPage=1&criteria.id=000034C0-5928-4058-A265-16834A1F9ECD">根据主任务Id查询定时任务执行情况(job/getJobDetailDataListOnPage.action?criteria.paging.maxResults=40&criteria.paging.currentPage=1&criteria.id=000034C0-5928-4058-A265-16834A1F9ECD)</a>
	<p />
	<br />
	<a href="job/getJobDetailDataListOnPage.action?criteria.paging.maxResults=40&criteria.paging.currentPage=1&criteria.jobItemId=00000249-9804-4593-A8B9-64DD55C6A1ED">根据子任务Id查询定时任务执行情况(job/getJobDetailDataListOnPage.action?criteria.paging.maxResults=40&criteria.paging.currentPage=1&criteria.jobItemId=00000249-9804-4593-A8B9-64DD55C6A1ED)</a>			
	<p />
	<br />
	<a href="job/getJobDetailDataListForJobsBeingProcessedOnPage.action?criteria.paging.maxResults=40&criteria.paging.currentPage=1&criteria.poolId=yihaodian/web-pool-simulator&criteria.triggerId=yhdCronTrigger_kiraClientTestCanceledFailedService-executeJobFailed-asynchronous-onlyRunOnSingleProcess">查询和某个定时任务相关的正在被处理的任务的详细信息(job/getJobDetailDataListForJobsBeingProcessedOnPage.action?criteria.paging.maxResults=40&criteria.paging.currentPage=1&criteria.poolId=yihaodian/web-pool-simulator&criteria.triggerId=yhdCronTrigger_kiraClientTestCanceledFailedService-executeJobFailed-asynchronous-onlyRunOnSingleProcess)</a>	
	<p />
	<br />
	<a href="job/manuallyReRunJob.action?criteria.id=AAAAAAA">手动重跑任务(job/manuallyReRunJob.action?criteria.id=AAAAAAA)</a>
	<p />
	<br />
	<a href="job/cancelJob.action?criteria.id=AAAAAAA">取消执行任务(job/cancelJob.action?criteria.id=AAAAAAA)</a>
	<p />
	<br />
	<a href="job/cancelJob.action?criteria.id=AAAAAAA&criteria.cancelJobJsonMapString={'param1':10,'param2':'aaa'}">带参数取消执行任务(job/cancelJob.action?criteria.id=AAAAAAA&criteria.cancelJobJsonMapString={'param1':10,'param2':'aaa'})</a>					
	<p />
	<br />
	<a href="job/archiveForJobData.action?criteria.newTableNameSuffixForArchive=test&criteria.startTimeForArchive=2012-09-01 00:00:00&criteria.endTimeForArchive=2012-10-01 00:00:00">对定时任务运行数据进行归档(job/archiveForJobData.action?criteria.newTableNameSuffixForArchive=test&criteria.startTimeForArchive=2013-09-01 00:00:00&criteria.endTimeForArchive=2013-10-01 00:00:00)</a>					
	<p />
	<br />	
	<a href="jobHistory/getJobHistoryDetailDataListOnPage.action?criteria.paging.maxResults=11&criteria.jobId=0017FD73-E2B9-4C48-B472-32FD1F69FE13">定时任务执行各阶段状态变化查询(jobHistory/getJobHistoryDetailDataListOnPage.action?criteria.paging.maxResults=11&criteria.jobId=0017FD73-E2B9-4C48-B472-32FD1F69FE13)</a>	
	<p />
	<br />
	<a href="jobHistory/archiveForJobHistoryData.action?criteria.newTableNameSuffixForArchive=test&criteria.startTimeForArchive=2012-09-01 00:00:00&criteria.endTimeForArchive=2012-10-01 00:00:00">对定时任务运行时的状态变化数据进行归档(jobHistory/archiveForJobHistoryData.action?criteria.newTableNameSuffixForArchive=test&criteria.startTimeForArchive=2012-09-01 00:00:00&criteria.endTimeForArchive=2012-10-01 00:00:00)</a>	
	<p />
	<br />	
	<a href="jobItem/getJobItemDetailDataListOnPage.action?criteria.paging.maxResults=11&criteria.jobId=0017FD73-E2B9-4C48-B472-32FD1F69FE13">定时任务执行的详细信息(jobItem/getJobItemDetailDataListOnPage.action?criteria.paging.maxResults=10&criteria.jobId=0017FD73-E2B9-4C48-B472-32FD1F69FE13)</a>
	<p />
	<br />
	<a href="jobItem/archiveForJobItemData.action?criteria.newTableNameSuffixForArchive=test&criteria.startTimeForArchive=2012-09-01 00:00:00&criteria.endTimeForArchive=2012-10-01 00:00:00">对定时任务运行时的子任务数据进行归档(jobItem/archiveForJobItemData.action?criteria.newTableNameSuffixForArchive=test&criteria.startTimeForArchive=2012-09-01 00:00:00&criteria.endTimeForArchive=2012-10-01 00:00:00)</a>		
	<p />
	<br />
	<a href="jobItemHistory/getJobItemHistoryDetailDataListOnPage.action?criteria.paging.maxResults=12&criteria.jobItemId=E3561303-CC37-443E-B2A8-D72593746BFD">定时任务的子任务各阶段状态变化查询(jobItemHistory/getJobItemHistoryDetailDataListOnPage.action?criteria.paging.maxResults=12&criteria.jobItemId=E3561303-CC37-443E-B2A8-D72593746BFD)</a>
	<p />
	<br />
	<a href="jobItemHistory/archiveForJobItemHistoryData.action?criteria.newTableNameSuffixForArchive=test&criteria.startTimeForArchive=2012-09-01 00:00:00&criteria.endTimeForArchive=2012-10-01 00:00:00">对定时任务子任务运行时的状态变化数据进行归档(jobItemHistory/archiveForJobItemHistoryData.action?criteria.newTableNameSuffixForArchive=test&criteria.startTimeForArchive=2012-09-01 00:00:00&criteria.endTimeForArchive=2012-10-01 00:00:00)</a>						
	<p />
	<br />
	<a href="appCenter/getAppCenterDetailDataList.action?criteria.paging.maxResults=13">集中式执行环境管理(appCenter/getAppCenterDetailDataList.action?criteria.paging.maxResults=13)</a>
	<p />
	<br />
	<a href="kiraServer/getKiraServerDetailDataList.action?criteria.paging.maxResults=14">调度服务器管理(kiraServer/getKiraServerDetailDataList.action?criteria.paging.maxResults=14)</a>
	<p />
	<br />
	<a href="operation/list.action">查询所有操作列表(operation/list.action)</a>	
	<p />
	<br />
	<a href="operation/listOnPage.action?criteria.paging.maxResults=15">分页查询操作列表(operation/listOnPage.action?criteria.paging.maxResults=15)</a>
	<p />
	<br />
	<a href="operation/getAllNotReadonlyOperations.action">查询所有非只读操作(operation/getAllNotReadonlyOperations.action)</a>	
	<p />
	<br />
	<a href="operationLog/listOnPage.action?criteria.paging.maxResults=20">操作日志查询(分页)(operationLog/listOnPage.action?criteria.paging.maxResults=20)</a>
	<p />
	<br />
	<a href="operationLog/getOperationLogDetailDataListOnPage.action?criteria.paging.maxResults=5&criteria.operatedBy=xxx&criteria.resultCode=&criteria.operationName=&criteria.operationType=">分页查询操作日志详细信息(operationLog/getOperationLogDetailDataListOnPage.action?criteria.paging.maxResults=5&criteria.operatedBy=xxx&criteria.resultCode=&criteria.operationName=&criteria.operationType=)</a>
	<p />
	<br />
	<a href="jobTimeoutTracker/list.action">查询jobTimeoutTracker表全部数据(jobTimeoutTracker/list.action)</a>							
	<p />
	<br />
	<a href="jobTimeoutTracker/listOnPage.action?criteria.paging.maxResults=5">分页查询jobTimeoutTracker表数据(jobTimeoutTracker/listOnPage.action?criteria.paging.maxResults=5)</a>								
	<p />
	<br />
	<a href="timerTriggerSchedule/list.action">查询timerTriggerSchedule表全部数据(timerTriggerSchedule/list.action)</a>							
	<p />
	<br />
	<a href="timerTriggerSchedule/listOnPage.action?criteria.paging.maxResults=5">分页查询timerTriggerSchedule表数据(timerTriggerSchedule/listOnPage.action?criteria.paging.maxResults=5)</a>								
	<p />
	<br />	
	<a href="timerTriggerSchedule/getAllMisfiredTimerTriggerScheduleList.action">查询所有漏执行的timerTriggerSchedule列表(timerTriggerSchedule/getAllMisfiredTimerTriggerScheduleList.action)</a>							
	<p />
	<br />	
	<a href="qrtzTriggers/list.action">查询QRTZ_TRIGGERS表全部数据(qrtzTriggers/list.action)</a>							
	<p />
	<br />
	<a href="qrtzTriggers/listOnPage.action?criteria.paging.maxResults=5">分页查询QRTZ_TRIGGERS表数据(qrtzTriggers/listOnPage.action?criteria.paging.maxResults=5)</a>								
	<p />
	<br />	
	<a href="qrtzSimpleTriggers/list.action">查询QRTZ_SIMPLE_TRIGGERS表全部数据(qrtzSimpleTriggers/list.action)</a>							
	<p />
	<br />
	<a href="qrtzSimpleTriggers/listOnPage.action?criteria.paging.maxResults=5">分页查询QRTZ_SIMPLE_TRIGGERS表数据(qrtzSimpleTriggers/listOnPage.action?criteria.paging.maxResults=5)</a>								
	<p />
	<br />	
	<a href="qrtzFiredTriggers/list.action">查询QRTZ_FIRED_TRIGGERS表全部数据(qrtzFiredTriggers/list.action)</a>							
	<p />
	<br />
	<a href="qrtzFiredTriggers/listOnPage.action?criteria.paging.maxResults=5">分页查询QRTZ_FIRED_TRIGGERS表数据(qrtzFiredTriggers/listOnPage.action?criteria.paging.maxResults=5)</a>								
	<p />
	<br />	
	<p />
	<p />
	<div>---------------------start admin usage</div>
	<p />
	<br />
	<a href="kiraServer/startServer.action?criteria.clusterInternalServiceUrl=">startServer(kiraServer/startServer.action?criteria.clusterInternalServiceUrl=)</a>
	<p />
	<br />
	<a href="kiraServer/stopServer.action?criteria.clusterInternalServiceUrl=">stopServer(kiraServer/stopServer.action?criteria.clusterInternalServiceUrl=)</a>
	<p />
	<br />
	<a href="kiraServer/restartServer.action?criteria.clusterInternalServiceUrl=">restartServer(kiraServer/restartServer.action?criteria.clusterInternalServiceUrl=)</a>
	<p />
	<br />
	<a href="kiraServer/destroyServer.action?criteria.clusterInternalServiceUrl=">destroyServer(kiraServer/destroyServer.action?criteria.clusterInternalServiceUrl=)</a>
	<p />
	<br />	
	<a href="kiraServer/recoverServer.action?criteria.clusterInternalServiceUrl=">recoverServer(kiraServer/recoverServer.action?criteria.clusterInternalServiceUrl=)</a>
	<p />
	<br />	
	<a href="kiraServer/addServerIdToAssignedServerIdBlackList.action?criteria.assignedServerIdInBlackList=">addServerIdToAssignedServerIdBlackList(kiraServer/addServerIdToAssignedServerIdBlackList.action?criteria.assignedServerIdInBlackList=)</a>
	<p />
	<br />	
	<a href="kiraServer/removeServerIdFromAssignedServerIdBlackList.action?criteria.assignedServerIdInBlackList=">removeServerIdFromAssignedServerIdBlackList(kiraServer/removeServerIdFromAssignedServerIdBlackList.action?criteria.assignedServerIdInBlackList=)</a>
	<p />
	<br />	
	<a href="kiraServer/setAssignedServerIdBlackList.action?criteria.assignedServerIdBlackList=">setAssignedServerIdBlackList(kiraServer/setAssignedServerIdBlackList.action?criteria.assignedServerIdBlackList=)</a>
	<p />
	<br />	
	<a href="kiraServer/clearAssignedServerIdBlackList.action">clearAssignedServerIdBlackList(kiraServer/clearAssignedServerIdBlackList.action)</a>


	<%--

	--%>	
	<div>---------------------end admin usage</div>															
</body>
</html>